FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .

RUN python -m pip install --upgrade pip \
    && yum install gcc -y \
    && pip install --no-cache-dir -r requirements.txt

COPY models ./models
COPY __init__.py .
COPY lambda_function.py .
COPY .env .

CMD [ "lambda_function.lambda_handler" ] 