import re
import numpy as np
import pandas as pd

csv_file = "intent_classifier_samples.csv"

Category = "Direct book queries that request by title, series, author, genre, rating, popularity, language"
Category = "System queries about the book recommender application"
Label = 7
Notes = "Synthetic"
# Notes = "Real"

synth_samples = """
1. Can you recommend any books by Neil Gaiman?
2. I'm interested in exploring the mystery genre. What titles do you recommend?
3. Are there any highly-rated fantasy series you could suggest?
4. Do you carry any popular novels by female authors?
5. Could you point me towards some award-winning science fiction books?
6. I'm searching for historical novels set in ancient Rome. Any recommendations?
7. What are the top-rated literature classics of all time?
8. I'm curious about books that have been translated into multiple languages. Any suggestions?
9. Looking for a gripping thriller series to dive into. Any recommendations?
10. Do you have any humorous novels that will make me laugh out loud?
11. I'm in the mood for a thought-provoking philosophy read. Any recommendations?
12. Can you recommend a biography about a prominent historical figure?
13. I'm interested in exploring horror novels. What are some popular titles?
14. I'm looking for children's books that promote diversity and inclusion. Any suggestions?
15. Are there any highly acclaimed memoirs written by authors of color?
16. Could you recommend a short story collection that showcases diverse voices?
17. I'm intrigued by religious literature. What titles do you have in that genre?
18. What are the top-rated historical fiction novels of the past decade?
19. Do you have any humorous crime fiction novels in stock?
20. I'm on the hunt for thought-provoking teen reads. Any recommendations?
"""

synth_samples = """
Do you have Harry Potter?
Do you have the Broken Earth series?
Do you have All Quiet on the Western Front?
Do you have anything by Kazuo Ishiguro?
I'm looking for books by Celeste Ng.
What do you have in stock written by Madeline Miller?
I prefer nonfiction.
I love science fiction books.
Do you have a historical fiction section?
What are some classic books that everyone should read?
What are your most popular books?
What are your most beloved books?
What books do you have in French?
Do you have any Spanish-language books?
I'm looking for books in Italian.
I'm doing research for an essay, and I'm looking for best-selling history books about the American Civil War.
Do you have any popular young adult fantasy series?
Do you have any memoirs by French authors?
"""

synth_samples = """
- Can you explain the algorithm behind your book recommendations?
- How does your system determine which books to recommend to users?
- Could you walk me through the technology stack powering your recommendation engine?
- Are there any specific criteria your application uses to suggest books?
- What data sources does your recommender system rely on?
- Do you take user preferences into account when making book suggestions?
- Can users provide feedback to improve the accuracy of your recommendations?
- How often are the recommendations updated in your system?
- Is there a personalized aspect to the book recommendations you provide?
- What features differentiate your book recommendation system from others in the market?
- Do you have any plans to incorporate more genres into your recommendation engine?
- How do you handle new book releases in your recommendation algorithm?
- What role does user engagement play in refining the book suggestions?
- Are there any external factors that influence the recommendations generated by your system?
- Can users customize the criteria used for book recommendations?
- How do you ensure diversity and inclusivity in the books that are recommended?
- Are there any privacy measures in place to protect user data in your recommendation system?
- How do you handle outliers or unique preferences when suggesting books?
- What metrics do you use to evaluate the effectiveness of your recommendation system?
- Can you share any success stories or user testimonials related to your book recommendations?
"""

split_samples = re.split(r"\n", synth_samples)
# print(split_samples)

# Remove list numbering if needed
pattern = re.compile(r"^\d+.\s*")
# pattern = re.compile(r"^-\s*")
split_samples = [pattern.sub("", sample) for sample in split_samples]
# print(split_samples)

n = len(split_samples)
sample_dict = {
    "Query": split_samples,
    "Label": np.ones(n)*Label,
    "Notes": [Notes]*n,
    "Category": [Category]*n,
}

sample_df = pd.DataFrame.from_dict(sample_dict)
sample_df = sample_df.loc[sample_df["Query"].apply(lambda x: len(x)>0)] # remove empty strings

sample_df.to_csv(csv_file, mode="a", index=False, header=False)