# ───────────────────────────────
# configs/exp_rf_grid.yaml
# ───────────────────────────────
experiment_name: rf_gridsearch_001
task_type: grid_search

pipeline_kwargs:
  use_title: true
  use_fare: true
  model: rf

param_grid:
  clf__n_estimators: [100, 200]
  clf__max_depth: [3, 5, 10]

cv:
  n_splits: 5
  shuffle: true
  random_state: 42

scoring: accuracy