experiment_name: 000_example
data_prep:
  type: DynamicDataPrepPipeline
  params:
    ordinal_columns:
    - Sex
    numeric_columns:
    - Age
    - Pclass
    - Fare
    extract_title: true
    extract_fam: true
    extract_deck: true
    extract_sexpclassage: true
model:
  type: RandomForestClassifier
  params:
    max_depth: 20
    random_state: 0
splitter:
  type: StratifiedKFold
  params:
    n_splits: 5
    shuffle: true
    random_state: 0
numeric_transformations:
  Fare:
    type: Pipeline
    steps:
    - name: bin
      transformer:
        type: KBinsDiscretizer
        params:
          n_bins: 4
          encode: ordinal
    - name: scale
      transformer:
        type: MinMaxScaler
  Pclass:
    type: MinMaxScaler
age_imputer_model:
  type: RandomForestRegressor
  params:
    max_depth: 20
param_grid:
- data_prep__ordinal_columns:
  - - Sex
  data_prep__numeric_columns:
  - - Age
    - Pclass
    - Fare
  data_prep__extract_title:
  - false
  - true
  data_prep__extract_fam:
  - false
  - true
  data_prep__extract_deck:
  - false
  - true
  data_prep__extract_sexpclassage:
  - false
  - true
  model__max_depth:
  - 5
  - 20
