experiment_name: 004b_age_imputer_cv
data_prep:
  type: DynamicDataPrepPipeline
  params:
    extract_title: true
    extract_fam: true
    numeric_columns:
    - SibSp
    - Pclass
    - Fare
numeric_transformations:
  default: passthrough
model:
  type: RandomForestRegressor
  params:
    max_depth: 4
    n_estimators: 10
    random_state: 0
splitter:
  type: KFold
  params:
    n_splits: 5
    shuffle: true
    random_state: 0
target: Age
